server:
  shutdown: graceful
  port: 10000

spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/test
    username: root
    password: smartnews
  datasource:
    test:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: smartnews1
      pool-name: testDBPool
      max-lifetime: 580000